name: Lint
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows:
      - CIbuild
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
