name: Publish GitHub Actions Artifacts Example

on: push

jobs:
  NodeCI:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: assets-for-download
          path: downloads
